language: python
python:
  # - "2.5"
  # - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - git config --global user.email "auto-version-test@travis.ci"
  - git config --global user.name "Testing on Travis CI"
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests
